window.__Q__ = {
legs:[
{t:'① Jarred → Seoul, business', d:'Sun 27 Sep · 1 pax · SMF or SFO → ICN',
 opts:[
 {v:'CONFIRMED',n:'Korean Air KE024 — SFO 12:50 → ICN 17:20+1, NONSTOP 12h30',bed:'yes',p:4304,pick:true,
  s:'Median of 4 sources ($4,131 momondo – $4,412 Kayak, 6.8% spread — book the specific source). Prestige. ⚠ 777-300ER rotates between three cabins: the 40-seat 1-2-1 Suites 2.0 and the 42-seat 2-2-2 are both fine, the 56-seat 2-3-2 Sleeper has trapped middles. Check the seat map at booking.'},
 {v:'CONFIRMED',n:'United UA893 — SFO 10:25 → ICN 15:00+1, NONSTOP 12h35, Polaris',bed:'yes',p:4411,
  s:'3 sources exact. True 1-2-1. Points: 87,500 via LifeMiles or Aeroplan (both Amex 1:1) — not United directly.'},
 {v:'CONFLICTING',n:'Asiana OZ211 — SFO 23:20 → ICN 04:25+2, NONSTOP 13h05',bed:'yes',p:'$4,112–4,870',
  s:'A350-900, 28 Business Smartium 1-2-1, 77in bed. Points: 85,000 Aeroplan or LifeMiles, both Amex-reachable.'},
 {v:'CONFIRMED',n:'Delta-branded via Seattle, 16h54 — the cheaper Delta option',bed:'yes',p:4379,
  s:'4 sources. $765 CHEAPER than the itinerary in your app screenshot, and 10 min shorter. Sources disagree on whether the ocean leg is Delta or Korean metal.'},
 {v:'CONFIRMED',n:'Delta One via Seattle, 17h04 — the exact flight in your screenshot',bed:'yes',p:5144,
  s:'3 sources agree to the dollar. A350-900, 32 Delta One suites with doors. POINTS: 348,500 SkyMiles + $6 — you hold 132,931, short by 215,569. Topping up costs 215,569 MR + ~$99 Amex fee and returns 1.48¢/mile. Poor.'},
 {v:'CONFIRMED',n:'Same itinerary, Delta Main Cabin',bed:'no',p:866,s:'If the bed is not worth $4,278.'},
 {v:'CONFLICTING',n:'Same itinerary, Delta Premium Select',bed:'no',p:1411,s:'Recliner, not flat.'}]},

{t:'② The three employees → Seoul, economy', d:'Sun 27 Sep · 3 pax · SFO → ICN',
 opts:[
 {v:'CONFIRMED',n:'Asiana nonstop — SFO 23:20 → ICN 04:25+2',p:1254,pick:true,
  s:'$418 each. Beats every other nonstop by ~$1,050 for the three of them.'},
 {v:'CONFLICTING',n:'China Airlines via Taipei — cheapest 1-stop',p:1725,s:'Not worth the stop for $471.'},
 {v:'CONFIRMED',n:'Korean Air nonstop / United nonstop — both',p:2300,s:'Arrive a day earlier than Asiana.'},
 {v:'CONFIRMED',n:'Delta via Seattle',p:2313,s:'The routing you asked about. Loses.'},
 {v:'CONFIRMED',n:'ORIGIN TEST — same trip out of Sacramento instead',p:1862,
  s:'SFO wins decisively. Fly them from SFO.'},
 {v:'CONFIRMED',n:'POINTS — Aeroplan on Asiana, 50,000/pp',p:'150,000 MR',
  s:'DO NOT USE. 150,000 MR to avoid $1,254 is well under 1¢/point.'}]},

{t:'③ All four men → Singapore', d:'Tue Oct 6 · locked by the Marina Bay Sands booking · ICN → SIN',
 opts:[
 {v:'CONFIRMED',n:'Jarred — Asiana OZ751, ICN 16:10 → SIN 21:30, business',bed:'yes',p:960,pick:true,
  s:'Cheapest AND the best seat of the group. Beats the KE643 you had penciled in by $35.'},
 {v:'CONFIRMED',n:'Jarred — Korean KE643, ICN 13:50 → SIN 19:15 (your original)',bed:'yes',p:995},
 {v:'CONFIRMED',n:'Jarred — Korean KE647 red-eye, ICN 23:35 → SIN 05:00+1',bed:'yes',p:995,s:'Arrives before hotel check-in.'},
 {v:'CONFIRMED',n:'Jarred — T\'way TW161, cheapest "business"',bed:'no',p:623,s:'LCC — not a real business cabin.'},
 {v:'SINGLE-SOURCE',n:'Team ×3, economy',p:528,s:'~$176 each, carried from the earlier live pull. Re-verify.'}]},

{t:'④ Ashley + 3 kids → Rome', d:'4 pax (Ezra and Silas price as adults) · SFO → FCO · THE DATE IS THE DECISION',
 opts:[
 {v:'CONFIRMED',n:'WED OCT 7 — ITA nonstop, 12h, economy',p:3014,pick:true,
  s:'★ ITA\'s AZ641 does NOT fly Thursdays — verified across a 6-day ladder. Oct 8 is also independently the worst-priced day in the window. Departing Oct 7 lands Oct 8 with THREE nights before the cruise instead of two.'},
 {v:'TWO-SOURCE',n:'★ WED OCT 7 — British Airways / Iberia BUSINESS via London, 1 stop, 4 pax',bed:'yes',p:'$9,492–10,097',
  s:'★ THE FIND OF THE WHOLE STUDY — this replaces the $16,862 nonstop below and saves $6,765–7,370. SINGLE TICKET, lie-flat on the SFO→LHR longhaul, ~14h50 total with a ~1h40 Heathrow connection. Google Flights $9,492, momondo $10,097 (~6% apart); both independently agree it is the cheapest business on the day.<br><br>⚠ <b>TWO sources, not three — badged honestly rather than letting a gap wear a CONFIRMED label.</b> The third attempt failed outright: the cabin encoding returned economy for both business AND first, so it measured nothing.<br><br>What closes the gap instead: both figures were then <b>re-run against your EXACT party</b> — 3 adults plus the 8-year-old, with Google echoing back "for 4 passengers" to prove the child registered — and came back <b>identical to the dollar</b>. Atticus pays full adult fare in business, same as economy. The same two engines also return the nonstop below at $16,862 to the dollar. Party composition is not hiding anything here.<br><br>The $600 spread is ticketing path: the cheap fare is PARTNER-ticketed via Finnair / Aer Lingus / Iberia, not BA direct ($4,238/pp). Partner-ticketed business can carry different change and cancel terms — read them at checkout, there is a nonrefundable cruise on the other end. Runner-up: Lufthansa via Munich, $2,948/pp = $11,792.'},
 {v:'CONFIRMED',n:'WED OCT 7 — United UA507 nonstop, BUSINESS, 4 pax',bed:'yes',p:16862,
  s:'Both engines return $16,862 TO THE DOLLAR — which is what validates the BA figure above: the same two sources that agree perfectly here disagree only 6% there. Still the best seat and the only nonstop, but you are paying ~$7,000 for the nonstop and one hour. Identical aircraft costs $26,334 on Oct 8.'},
 {v:'CONFIRMED',n:'THU OCT 8 — Condor via Frankfurt, 14h20, economy',p:1485,
  s:'Cheapest sane option if Oct 8 is fixed. "Economy Zero" — no checked bag, add ~$75–100/bag.'},
 {v:'CONFIRMED',n:'THU OCT 8 — Condor premium economy',p:3700,
  s:'3-source confirmed (Google $930 / Kayak $922 / momondo $922 pp). A real premium cabin for four.'},
 {v:'CONFIRMED',n:'THU OCT 8 — SAS via Copenhagen / TAP via Lisbon',p:'$1,936–1,947'},
 {v:'SINGLE-SOURCE',n:'THU OCT 8 — United UA507 nonstop, economy (the only nonstop that day)',p:5250},
 {v:'CONFIRMED',n:'POINTS — Flying Blue premium economy, Oct 8 only, 4 seats live-verified',p:'358,000 MR + $996',
  s:'0.76¢/point against the $3,700 cash equivalent. Burns ~$4,000 of value.'},
 {v:'CONFIRMED',n:'POINTS — Flying Blue business via LONDON, Oct 8 — REAL, AND NOW DEAD',bed:'yes',p:'454,000 MR + $1,810',
  s:'★ THE AWARD IS GENUINE — 113,500/pp, 4 seats, live-verified 100%, not a phantom. It is dead anyway, because the BA cash fare above kills it on identical geography. Against $9,492 avoided it returns 1.69¢ per point — BELOW the 1.8–2.0¢ Membership Rewards baseline, meaning burning 86% of your pool would LOSE money versus buying the ticket. And it is the worse product: AIR FRANCE/KLM metal (not Virgin), THREE FLIGHTS on TWO TICKETS — SFO → Paris or Amsterdam → London → Rome, flying past Rome to Paris then back northwest — flat on leg one only, no misconnect protection, a terminal transfer, a bag re-check, and two days of cruise buffer instead of three. Watch this number move: 3.3¢ → 1.83¢ → 1.69¢. The award never changed. Only the benchmark got honest — the first figure compared a three-flight backtrack against a NONSTOP, flattering it ~2×.'},
 {v:'CONFIRMED',n:'POINTS — everything else in business, both dates',p:'does not fit',
  s:'Flying Blue direct to Rome 778,000 · Turkish 700,000 · both over your 525,382. Lufthansa 309,540 is Miles & More, unreachable. A BA Avios 99,000 at $0 fees looked perfect and VANISHED when tested at 4 seats — a phantom in cached data.'}]},

{t:'⑤ Jarred → Rome', d:'Sat 10 Oct · 1 pax · SIN → FCO · must clear the Fri Oct 9 party and beat Oct 11 boarding',
 opts:[
 {v:'CONFIRMED',n:'Etihad via Abu Dhabi — both legs genuine lie-flat',bed:'yes',p:2093,pick:true,
  s:'Best fit for the constraint. ⚠ Amex → Etihad Guest was REMOVED 30 Jun 2026, so this is a cash buy.'},
 {v:'CONFIRMED',n:'Saudia via Jeddah, dep 02:20 — cheapest true lie-flat',bed:'yes',p:1588,
  s:'$505 less than Etihad. The 2:20am departure is the cost.'},
 {v:'CONFIRMED',n:'Emirates A380 on BOTH legs — true 1-2-1 throughout',bed:'yes',p:2423},
 {v:'CONFIRMED',n:'Emirates, the cheap one everyone books — THE TRAP',bed:'no',p:2222,
  s:'Not lie-flat. $201 less than the real A380 product for a materially worse seat.'},
 {v:'CONFLICTING',n:'Qatar Qsuite via Doha — best seat on the day',bed:'yes',p:2929},
 {v:'CONFIRMED',n:'★ THE 150,000-AVIOS QUESTION, RESOLVED: it is 75,000',p:'75,000 Avios',
  s:'Qatar Privilege Club, and Amex MR → Qatar Avios IS still live. My earlier 150,000 reading was wrong. At 75,000 against a $2,929 cash fare this is roughly 3.5¢/point — the best redemption in the entire study.'}]},

{t:'⑥ The three employees → home', d:'Sat 10 Oct · 3 pax · SIN → SFO or SMF',
 opts:[
 {v:'CONFIRMED',n:'Singapore Airlines SQ32 nonstop → SFO, bag-eligible fare',p:1393,pick:true,
  s:'$464 each on a nonstop. The winner.'},
 {v:'CONFIRMED',n:'Vietnam Airlines via Ho Chi Minh City',p:1473,s:'More stops, more money. No.'},
 {v:'CONFIRMED',n:'United nonstop, BASIC economy',p:1758,s:'$1,926 for the standard bag-eligible fare.'},
 {v:'CONFIRMED',n:'Through to Sacramento — Air Canada',p:1753,
  s:'⚠ VERDICT ON THE OLD CLAIM: flying them to SMF costs $360 MORE than SFO, not $70. The prior note was wrong.'}]},

{t:'⑦ Rome → Dubrovnik', d:'Sun 18 Oct · 5 pax · after the cruise',
 opts:[
 {v:'CONFIRMED',n:'Ryanair FR5975 nonstop — Family Plus bundle',p:305,pick:true,
  s:'The realistic booking for five with multi-week luggage. Basic fare alone is $115 but that is cabin-bag-only.'},
 {v:'CONFIRMED',n:'Ryanair FR5975 nonstop — Basic fare',p:115,s:'Under-seat bag only. Unrealistic here.'},
 {v:'CONFLICTING',n:'Croatia Airlines OU385 nonstop — the only alternative',p:825,
  s:'Timing does not work against the disembarkation. Ruled out on feasibility, not price.'},
 {v:'UNAVAILABLE',n:'ITA and Vueling nonstops',p:null,s:'Neither operates this route.'}]},

{t:'⑧ All five → home', d:'Oct 25 – Nov 3 · 5 pax · Europe → SFO · THE BIG ONE',
 opts:[
 {v:'CONFIRMED',n:'5 IN ECONOMY — London LHR → SFO, British Airways NONSTOP',p:2355,pick:true,
  s:'The winner for economy. Add ~$470 Ryanair from Dubrovnik.'},
 {v:'CONFIRMED',n:'2 BUSINESS + 3 ECONOMY — Dublin, cheapest business seats',bed:'yes',p:7047,pick:true,
  s:'The cheapest way to get two people flat. Booked as two separate PNRs.'},
 {v:'CONFIRMED',n:'2 BUSINESS + 3 ECONOMY — London, everyone on the nonstop',bed:'yes',p:7364,
  s:'$317 more than Dublin and nobody connects. Probably worth it.'},
 {v:'CONFIRMED',n:'5 IN BUSINESS — Dublin EI61 NONSTOP',bed:'yes',p:13491,
  s:'★ CORRECTS my earlier claim that five-in-business does not exist at Dublin. It does. A330, Thompson-style flat bed.'},
 {v:'CONFIRMED',n:'5 IN BUSINESS — London, Virgin VS19 NONSTOP',bed:'yes',p:14888,
  s:'$1,397 more than Dublin for the Upper Class cabin.'},
 {v:'CONFIRMED',n:'POINTS — CROATIA HAS ZERO BUSINESS AWARD SPACE',p:'none',
  s:'★ Dubrovnik, Split and Zagreb, all three, on all three of your dates, verified on BOTH axes (fresh data AND seat-count filter). Positioning out of Croatia by cash is not a preference — it is mandatory if you want award seats.'},
 {v:'CONFIRMED',n:'POINTS — FRA premium economy, 40,786/pp, NONSTOP, five seats',p:'~204,000 MR',
  s:'★ THE BEST POINTS VALUE FOUND FOR THE RETURN. Nov 3 or Nov 4, nonstop to SFO, five seats confirmed live. Nov 3 is inside your window; Nov 4 is one day past it.'},
 {v:'CONFIRMED',n:'POINTS — ZURICH is the only origin with FIVE business seats',bed:'yes',p:'Nov 2 or Nov 3',
  s:'If five flat beds on points is the goal, ZRH on Nov 2/3 is the single origin that has them on your actual dates. Requires positioning from Dubrovnik.'},
 {v:'CONFIRMED',n:'POINTS — MUNICH is the clean 2 business + 3 economy',bed:'yes',p:'Nov 2 or Nov 3',
  s:'Nonstop to SFO on both days. This is the answer to your original "2 biz then 3 econ" question: MUC, Nov 2 or Nov 3.'},
 {v:'SINGLE-SOURCE',n:'⚠ POINTS — FRA business Nov 4 — DO NOT TRANSFER ON THIS',p:'unverified',
  s:'★ RE-CHECK LIVE BEFORE MOVING A SINGLE POINT. This passed its seat filter on OLDER data — one axis green, one axis stale. That is the exact state the BA Avios 99,000/$0-fee row was in immediately before it evaporated under testing. It is also Nov 4, one day outside your window.'}]}
],
totals:{h:'The recommended plan, all cash, all confirmed',
 rows:[
 ['① Jarred → Seoul · Korean KE024 nonstop','$4,304'],
 ['② Team ×3 → Seoul · Asiana nonstop','$1,254'],
 ['③ Jarred → Singapore · Asiana OZ751 business','$960'],
 ['③ Team ×3 → Singapore · economy','$528'],
 ['④ Ashley + 3 kids → Rome · ITA nonstop, WED OCT 7','$3,014'],
 ['⑤ Jarred → Rome · Etihad, both legs flat','$2,093'],
 ['⑥ Team ×3 → home · Singapore SQ32 nonstop','$1,393'],
 ['⑦ Rome → Dubrovnik · Ryanair Family Plus ×5','$305'],
 ['⑧ All five → home · London nonstop, 2 flat + 3 economy','$7,364'],
 ['Positioning Dubrovnik → London · Ryanair ×5','$470']],
 gl:'ALL FLIGHTS, ALL 8 TRAVELLERS',gv:'$21,685',
 note:'Swap ⑧ to all-economy and the total drops to <b>$16,676</b>. Swap it to five flat beds out of Dublin and it rises to <b>$27,394</b>.<br><br><b>The family-in-business upgrade is now genuinely affordable.</b> Putting Ashley and the three kids in lie-flat to Rome used to mean the $16,862 nonstop, a $13,848 jump. On the BA 1-stop it is <b>+$6,478</b>, taking the all-in to <b>$28,163</b>. That is the single biggest quality-per-dollar decision left on the table. Hotels and the cruise are separate and already booked.'},
notes:[
{h:'The one points play worth making',
 b:'<b>Qatar Avios, 75,000, for Jarred\'s Singapore → Rome leg.</b> Amex MR transfers 1:1 and that partnership is still live. Against the $2,929 Qsuite cash fare it returns roughly <b>3.5¢ per point</b> — the best redemption found anywhere in this study, and it uses 14% of your pool. Everything else tested came in under 1.5¢ or sat in a program you cannot reach.'},
{h:'The Rome decision — RESOLVED, and it moved $7,000',
 b:'This was framed as a cash-versus-points choice. It is not one any more, because a third option turned up that beats both. <b>British Airways business, Wed Oct 7, SFO → London → Rome, ~$9,492–10,097 for four.</b> Single ticket, lie-flat on the ocean crossing, ~14h50 door to door, lands Oct 8 with three clear days before boarding. That is <b>$6,765–7,370 cheaper than the United Polaris nonstop</b> and roughly <b>$16,000 cheaper than flying business on Oct 8</b>.<br><br>It survived the test that killed everything else: two independent engines priced it, and <i>the same two engines returned the nonstop at $16,862 to the dollar</i>. Sources that agree perfectly on one fare and 6% apart on another are measuring, not guessing.<br><br>You give up two things. The connection is real — <b>~1h40 at Heathrow for four people with bags</b>, which is legal but tight; single-ticket protection makes a misconnect a delay rather than a trip-ender, and that protection is exactly what the points itinerary lacked. And the cheap fare is <b>partner-ticketed via Finnair, Aer Lingus or Iberia</b> rather than BA direct, which is where the $600 spread comes from and where the change and cancel terms may differ. Read those terms at checkout; there is a cruise on the other end of this flight.<br><br><b>Do not use miles on this leg in any cabin.</b> Against the honest denominator the business award returns 1.69¢/point and the premium-economy award 0.76¢ — both below what the points are already worth sitting still.'},
{h:'Why the numbers kept moving — and why these ones should hold',
 b:'Two of the corrections that mattered most in this study came from <b>challenging a comparison, not from searching harder</b>. The Rome award was reported at 3.3¢ per point, then 1.83¢, then 1.69¢ — the award itself never changed once. What changed is that the first number benchmarked a three-flight backtrack against a <i>nonstop</i> cash fare, which inflated it roughly 2×. Pricing the honest denominator is also what surfaced the BA fare that ended up saving $7,000. Separately, filtering award results by seat count killed two findings that had looked clean and specific.<br><br>The durable rule underneath both, and the one worth carrying into the actual booking: <b>a filter asserted at query time and the age of the data it was asserted against are independent failure modes. A result is only trustworthy when both are green.</b> Every "N/A" and every "re-check live" on this page is a place where exactly one of them was.<br><br>Three separate things in this study failed the same way: seats.aero\'s seat counts, its <b>$0</b> tax fields, and a search engine\'s cabin-class parameter. <b>None of them returned an error. All three returned a plausible wrong number instead.</b> That is why the badges exist, and why "re-check live before transferring" appears where it does.'},
{h:'What changed versus what you were told before',
 b:'Delta One is <b>348,500 SkyMiles, not 94,000</b> — out of reach. Flying the team from Sacramento costs <b>$360 more</b>, not $70 less. Dublin <b>does</b> sell five business seats ($13,491) — my earlier "caps at 4" was wrong. The Qatar award is <b>75,000 Avios, not 150,000</b>. ITA does not fly to Rome on Thursdays, which makes Oct 7 worth $2,236 in economy or $9,472 in business. And Amex removed Etihad Guest as a transfer partner on 30 June 2026.'}]
};
