window.__Q__ = {
legs:[
{t:'① Jarred → Seoul, business', d:'Sun 27 Sep · 1 pax · SMF or SFO → ICN',
 opts:[
 {v:'CONFIRMED',n:'Korean Air KE024 — SFO 12:50 → ICN 17:20+1, NONSTOP 12h30',bed:'yes',p:4304,pick:true,
  s:'Median of 4 sources ($4,131 momondo – $4,412 Kayak, 6.8% spread — book the specific source). Prestige. ⚠ 777-300ER rotates between three cabins: the 40-seat 1-2-1 Suites 2.0 and the 42-seat 2-2-2 are both fine, the 56-seat 2-3-2 Sleeper has trapped middles. Check the seat map at booking.'},
 {v:'CONFIRMED',n:'United UA893 — SFO 10:25 → ICN 15:00+1, NONSTOP 12h35, Polaris',bed:'yes',p:4411,
  s:'3 sources exact. True 1-2-1. Points: 87,500 via LifeMiles or Aeroplan (both Amex 1:1) — not United directly.'},
 {v:'CONFLICTING',n:'Asiana OZ211 — SFO 23:20 → ICN 04:25+2, NONSTOP 13h05',bed:'yes',p:'$4,112–4,870',
  s:'A350-900, 28 Business Smartium 1-2-1, 77in bed. Points: 85,000 Aeroplan or LifeMiles, both Amex-reachable.'},
 {v:'CONFIRMED',n:'Delta-branded via Seattle, 16h54 — the cheaper Delta option',bed:'yes',p:4379,
  s:'4 sources. $765 CHEAPER than the itinerary in your app screenshot, and 10 min shorter. Sources disagree on whether the ocean leg is Delta or Korean metal.'},
 {v:'CONFIRMED',n:'Delta One via Seattle, 17h04 — the exact flight in your screenshot',bed:'yes',p:5144,
  s:'3 sources agree to the dollar. A350-900, 32 Delta One suites with doors. POINTS: 348,500 SkyMiles + $6 — you hold 132,931, short by 215,569. Topping up costs 215,569 MR + ~$99 Amex fee and returns 1.48¢/mile. Poor.'},
 {v:'CONFIRMED',n:'Same itinerary, Delta Main Cabin',bed:'no',p:866,s:'If the bed is not worth $4,278.'},
 {v:'CONFLICTING',n:'Same itinerary, Delta Premium Select',bed:'no',p:1411,s:'Recliner, not flat.'}]},

{t:'② The three employees → Seoul, economy', d:'Sun 27 Sep · 3 pax · SFO → ICN',
 opts:[
 {v:'CONFIRMED',n:'Asiana nonstop — SFO 23:20 → ICN 04:25+2',p:1254,pick:true,
  s:'$418 each. Beats every other nonstop by ~$1,050 for the three of them.'},
 {v:'CONFLICTING',n:'China Airlines via Taipei — cheapest 1-stop',p:1725,s:'Not worth the stop for $471.'},
 {v:'CONFIRMED',n:'Korean Air nonstop / United nonstop — both',p:2300,s:'Arrive a day earlier than Asiana.'},
 {v:'CONFIRMED',n:'Delta via Seattle',p:2313,s:'The routing you asked about. Loses.'},
 {v:'CONFIRMED',n:'ORIGIN TEST — same trip out of Sacramento instead',p:1862,
  s:'SFO wins decisively. Fly them from SFO.'},
 {v:'CONFIRMED',n:'POINTS — Aeroplan on Asiana, 50,000/pp',p:'150,000 MR',
  s:'DO NOT USE. 150,000 MR to avoid $1,254 is well under 1¢/point.'}]},

{t:'③ All four men → Singapore', d:'Tue Oct 6 · locked by the Marina Bay Sands booking · ICN → SIN',
 opts:[
 {v:'CONFIRMED',n:'Jarred — Asiana OZ751, ICN 16:10 → SIN 21:30, business',bed:'yes',p:960,pick:true,
  s:'Cheapest AND the best seat of the group. Beats the KE643 you had penciled in by $35.'},
 {v:'CONFIRMED',n:'Jarred — Korean KE643, ICN 13:50 → SIN 19:15 (your original)',bed:'yes',p:995},
 {v:'CONFIRMED',n:'Jarred — Korean KE647 red-eye, ICN 23:35 → SIN 05:00+1',bed:'yes',p:995,s:'Arrives before hotel check-in.'},
 {v:'CONFIRMED',n:'Jarred — T\'way TW161, cheapest "business"',bed:'no',p:623,s:'LCC — not a real business cabin.'},
 {v:'SINGLE-SOURCE',n:'Team ×3, economy',p:528,s:'~$176 each, carried from the earlier live pull. Re-verify.'}]},

{t:'④ Ashley + 3 kids → Rome', d:'4 pax (Ezra and Silas price as adults) · SFO → FCO · THE DATE IS THE DECISION',
 opts:[
 {v:'CONFIRMED',n:'WED OCT 7 — ITA nonstop, 12h, economy',p:3014,pick:true,
  s:'★ ITA\'s AZ641 does NOT fly Thursdays — verified across a 6-day ladder. Oct 8 is also independently the worst-priced day in the window. Departing Oct 7 lands Oct 8 with THREE nights before the cruise instead of two.'},
 {v:'CONFIRMED',n:'WED OCT 7 — TAP BUSINESS via Lisbon, 1 stop, 17h20 — CHEAPEST AIRLINE-DIRECT BUSINESS',bed:'yes',p:13575,
  s:'★ <b>THE SURVIVOR.</b> Confirmed independently by two agents on separate instances, and it matches a TAP figure pulled days earlier — three sightings, no drift. It also prices identically on Oct 7 and Oct 8, which rules out the repeated-artifact suspicion that killed other rows. <b>Single ticket, genuine 1-2-1 lie-flat throughout</b>, $3,287 under the Polaris nonstop.<br><br>The cost is time: <b>17h20 versus 11h50</b> — about five and a half extra hours and a Lisbon connection, with an 8-year-old. That is the whole trade.<br><br>Two cheaper-looking rows near this price were tested and rejected: a JetBlue/Icelandair itinerary at $13,840 is <b>mixed-cabin recliner, not a bed</b>, and a LOT row at $16,719 carries a <b>12-hour layover</b>.'},
 {v:'CONFLICTING',n:'⚠ WED OCT 7 — British Airways BUSINESS via London, 1 stop — THE PRICE DEPENDS ON WHO SELLS IT',bed:'yes',p:'$10,097 or $14,454',
  s:'★ <b>RETRACTION. I called this a $9,492 fare and a ~$7,000 saving. It was never a fare at all.</b> Traced to source, the $9,492 was a price-filter control on the page — <code>aria-label="9492 US dollars"</code> with no carrier, no stop count, no duration attached. A text-flattened read put it next to the words "British Airways" and I paired two unrelated things. It was caught because a second agent could not reproduce it.<br><br><b>The replacement figure is real — and so is the one that contradicts it.</b> $14,454 reproduces as a complete row (16:35 → 16:55+1, 15h20, 2h20 Heathrow layover, emissions data). $16,941 reproduces too, as a 14h50 itinerary. <b>Each instance can see one and NOT the other.</b> The blindness is mutual, so neither is broken: <b>Google is serving divergent BA inventory on identical queries.</b><br><br>⚠ <b>That finding outranks the fare itself. Any single-instance cash quote on this route carries real variance</b> — mine included. Which is exactly why TAP is the recommendation: it is the one row sighted three times, on two instances, across two dates, without drifting a dollar.<br><br>Separately and genuinely, the same BA metal also sells through consolidators — momondo shows both on one screen: <b>$2,525/pp = $10,097</b> via Finnair / Aer Lingus / Iberia / Alaska (identical aircraft and seat) beside <b>"$4,238/pp directly with British Airways."</b> The "two sources agreeing within 6%" I originally leaned on was an OTA fare and an airline fare treated as one product.<br><br><b>15h20 total, T5-to-T5 connection, no terminal change.</b><br><br>⚠ <b>NOBODY HAS VERIFIED THE $10,097 ACTUALLY TICKETS.</b> That is the real open question on this leg. If it tickets, it is the cheapest lie-flat to Rome by a wide margin. If it does not, the airline-direct ladder is the whole story. Consolidator-ticketed business also carries change and cancel terms you do not control, with a nonrefundable cruise three days behind the flight.<br><br><b>WHAT THE SEAT ACTUALLY IS, either way.</b> SFO→LHR is BA286, normally a 777-300ER with the new <b>Club Suite</b> — 1-2-1, aisle access, closing door. Genuinely excellent. <b>LHR→FCO is Club Europe: a RECLINER</b>, an economy seat with the middle blocked. The bed exists on the ocean crossing only. The connection is <b>T5 to T5, no terminal change</b>, 1h40 — tight for four with an 8-year-old but structurally plausible, and single-ticket protection makes a miss a delay rather than a trip-ender. Reconfirm the Oct 7 aircraft closer in; BA sometimes swaps a 777-200ER and not all have Club Suite.'},
 {v:'CONFIRMED',n:'★ WED OCT 7 — United UA507 NONSTOP, BUSINESS, 4 pax — THE AIRLINE-DIRECT WINNER',bed:'yes',p:16862,
  s:'★ <b>The most solid number on this entire page</b> — every engine returns $16,862 TO THE DOLLAR across repeated runs and both party encodings. Polaris, 1-2-1, lie-flat the WHOLE way with no recliner second leg, 11h50, ONE flight, nothing to misconnect, lands Oct 8 with three clear days.<br><br>It is no longer the cheapest airline-direct business, but it is the best trip. The full Oct 7 airline-direct ladder: <b>TAP $13,575 (17h20) · BA $14,454 (15h20) · United nonstop $16,862 (11h50) · SWISS $16,942 · United/ITA $16,956 · ITA nonstop $21,270.</b> You are paying $3,287 over TAP to remove five and a half hours and a connection. With an 8-year-old that is a real trade, not a vanity one. Identical aircraft costs $26,334 on Oct 8 — the date still matters more than the carrier.'},
 {v:'CONFIRMED',n:'THU OCT 8 — Condor via Frankfurt, 14h20, economy',p:1485,
  s:'Cheapest sane option if Oct 8 is fixed. "Economy Zero" — no checked bag, add ~$75–100/bag.'},
 {v:'CONFIRMED',n:'THU OCT 8 — Condor premium economy',p:3700,
  s:'3-source confirmed (Google $930 / Kayak $922 / momondo $922 pp). A real premium cabin for four.'},
 {v:'CONFIRMED',n:'THU OCT 8 — SAS via Copenhagen / TAP via Lisbon',p:'$1,936–1,947'},
 {v:'SINGLE-SOURCE',n:'THU OCT 8 — United UA507 nonstop, economy (the only nonstop that day)',p:5250},
 {v:'CONFIRMED',n:'POINTS — Flying Blue premium economy, Oct 8 only, 4 seats live-verified',p:'358,000 MR + $996',
  s:'0.76¢/point against the $3,700 cash equivalent. Burns ~$4,000 of value.'},
 {v:'CONFIRMED',n:'POINTS — Flying Blue business via LONDON, Oct 8 — REAL, and worth 3.3¢ OR 1.8¢ depending on the comparison',bed:'yes',p:'454,000 MR + $1,810',
  s:'★ THE AWARD IS GENUINE — 113,500/pp, 4 seats, live-verified 100%, not a phantom. <b>Its value swings entirely on which cash fare you would otherwise have bought, so here are all three instead of the flattering one.</b><br><br>vs the <b>consolidator</b> BA fare ($10,097): <b>1.83¢</b> — a wash.<br>vs <b>TAP, the real airline-direct floor</b> ($13,575): <b>2.59¢</b> — clears the 1.8–2.0¢ MR baseline.<br>vs the <b>Polaris nonstop</b> ($16,862): <b>3.32¢</b> — strong, but the wrong comparison.<br><br><b>2.59¢ is the honest number</b>, and it makes this <i>marginal rather than compelling</i>: it clears the baseline while buying a structurally WORSE product than the cash fare it is measured against. TAP is one ticket and flat throughout; this is THREE FLIGHTS on TWO TICKETS (SFO → Paris or Amsterdam → London → Rome — flying past Rome, then back northwest), flat on leg one only, no misconnect protection between tickets, a terminal transfer, a bag re-check, and arriving Oct 9 with two days of cruise buffer. Spending 86% of your pool to fly a worse itinerary is not a win at any cents-per-point. <b>Do not use miles on this leg.</b>'},
 {v:'CONFIRMED',n:'POINTS — everything else in business, both dates',p:'does not fit',
  s:'Flying Blue direct to Rome 778,000 · Turkish 700,000 · both over your 525,382. Lufthansa 309,540 is Miles & More, unreachable. A BA Avios 99,000 at $0 fees looked perfect and VANISHED when tested at 4 seats — a phantom in cached data.'}]},

{t:'⑤ Jarred → Rome', d:'Sat 10 Oct · 1 pax · SIN → FCO · must clear the Fri Oct 9 party and beat Oct 11 boarding',
 opts:[
 {v:'CONFIRMED',n:'Etihad via Abu Dhabi — both legs genuine lie-flat',bed:'yes',p:2093,pick:true,
  s:'Best fit for the constraint. ⚠ Amex → Etihad Guest was REMOVED 30 Jun 2026, so this is a cash buy.'},
 {v:'CONFIRMED',n:'Saudia via Jeddah, dep 02:20 — cheapest true lie-flat',bed:'yes',p:1588,
  s:'$505 less than Etihad. The 2:20am departure is the cost.'},
 {v:'CONFIRMED',n:'Emirates A380 on BOTH legs — true 1-2-1 throughout',bed:'yes',p:2423},
 {v:'CONFIRMED',n:'Emirates, the cheap one everyone books — THE TRAP',bed:'no',p:2222,
  s:'Not lie-flat. $201 less than the real A380 product for a materially worse seat.'},
 {v:'CONFLICTING',n:'Qatar Qsuite via Doha — best seat on the day',bed:'yes',p:2929},
 {v:'CONFIRMED',n:'★ THE 150,000-AVIOS QUESTION, RESOLVED: it is 75,000',p:'75,000 Avios',
  s:'Qatar Privilege Club, and Amex MR → Qatar Avios IS still live. My earlier 150,000 reading was wrong. At 75,000 against a $2,929 cash fare this is roughly 3.5¢/point — the best redemption in the entire study.'}]},

{t:'⑥ The three employees → home', d:'Sat 10 Oct · 3 pax · SIN → SFO or SMF',
 opts:[
 {v:'CONFIRMED',n:'Singapore Airlines SQ32 nonstop → SFO, bag-eligible fare',p:1393,pick:true,
  s:'$464 each on a nonstop. The winner.'},
 {v:'CONFIRMED',n:'Vietnam Airlines via Ho Chi Minh City',p:1473,s:'More stops, more money. No.'},
 {v:'CONFIRMED',n:'United nonstop, BASIC economy',p:1758,s:'$1,926 for the standard bag-eligible fare.'},
 {v:'CONFIRMED',n:'Through to Sacramento — Air Canada',p:1753,
  s:'⚠ VERDICT ON THE OLD CLAIM: flying them to SMF costs $360 MORE than SFO, not $70. The prior note was wrong.'}]},

{t:'⑦ Rome → Dubrovnik', d:'Sun 18 Oct · 5 pax · after the cruise',
 opts:[
 {v:'CONFIRMED',n:'Ryanair FR5975 nonstop — Family Plus bundle',p:305,pick:true,
  s:'The realistic booking for five with multi-week luggage. Basic fare alone is $115 but that is cabin-bag-only.'},
 {v:'CONFIRMED',n:'Ryanair FR5975 nonstop — Basic fare',p:115,s:'Under-seat bag only. Unrealistic here.'},
 {v:'CONFLICTING',n:'Croatia Airlines OU385 nonstop — the only alternative',p:825,
  s:'Timing does not work against the disembarkation. Ruled out on feasibility, not price.'},
 {v:'UNAVAILABLE',n:'ITA and Vueling nonstops',p:null,s:'Neither operates this route.'}]},

{t:'⑧ All five → home', d:'Oct 25 – Nov 3 · 5 pax · Europe → SFO · THE BIG ONE',
 opts:[
 {v:'CONFIRMED',n:'5 IN ECONOMY — London LHR → SFO, British Airways NONSTOP',p:2355,pick:true,
  s:'The winner for economy. Add ~$470 Ryanair from Dubrovnik.'},
 {v:'CONFIRMED',n:'2 BUSINESS + 3 ECONOMY — Dublin, cheapest business seats',bed:'yes',p:7047,pick:true,
  s:'The cheapest way to get two people flat. Booked as two separate PNRs.'},
 {v:'CONFIRMED',n:'2 BUSINESS + 3 ECONOMY — London, everyone on the nonstop',bed:'yes',p:7364,
  s:'$317 more than Dublin and nobody connects. Probably worth it.'},
 {v:'CONFIRMED',n:'5 IN BUSINESS — Dublin EI61 NONSTOP',bed:'yes',p:13491,
  s:'★ CORRECTS my earlier claim that five-in-business does not exist at Dublin. It does. A330, Thompson-style flat bed.'},
 {v:'CONFIRMED',n:'5 IN BUSINESS — London, Virgin VS19 NONSTOP',bed:'yes',p:14888,
  s:'$1,397 more than Dublin for the Upper Class cabin.'},
 {v:'CONFIRMED',n:'POINTS — CROATIA HAS ZERO BUSINESS AWARD SPACE',p:'none',
  s:'★ Dubrovnik, Split and Zagreb, all three, on all three of your dates, verified on BOTH axes (fresh data AND seat-count filter). Positioning out of Croatia by cash is not a preference — it is mandatory if you want award seats.'},
 {v:'CONFIRMED',n:'POINTS — FRA premium economy, 40,786/pp, NONSTOP, five seats',p:'~204,000 MR',
  s:'★ THE BEST POINTS VALUE FOUND FOR THE RETURN. Nov 3 or Nov 4, nonstop to SFO, five seats confirmed live. Nov 3 is inside your window; Nov 4 is one day past it.'},
 {v:'CONFIRMED',n:'POINTS — ZURICH is the only origin with FIVE business seats',bed:'yes',p:'Nov 2 or Nov 3',
  s:'If five flat beds on points is the goal, ZRH on Nov 2/3 is the single origin that has them on your actual dates. Requires positioning from Dubrovnik.'},
 {v:'CONFIRMED',n:'POINTS — MUNICH is the clean 2 business + 3 economy',bed:'yes',p:'Nov 2 or Nov 3',
  s:'Nonstop to SFO on both days. This is the answer to your original "2 biz then 3 econ" question: MUC, Nov 2 or Nov 3.'},
 {v:'SINGLE-SOURCE',n:'⚠ POINTS — FRA business Nov 4 — DO NOT TRANSFER ON THIS',p:'unverified',
  s:'★ RE-CHECK LIVE BEFORE MOVING A SINGLE POINT. This passed its seat filter on OLDER data — one axis green, one axis stale. That is the exact state the BA Avios 99,000/$0-fee row was in immediately before it evaporated under testing. It is also Nov 4, one day outside your window.'}]}
],
totals:{h:'The recommended plan, all cash, all confirmed',
 rows:[
 ['① Jarred → Seoul · Korean KE024 nonstop','$4,304'],
 ['② Team ×3 → Seoul · Asiana nonstop','$1,254'],
 ['③ Jarred → Singapore · Asiana OZ751 business','$960'],
 ['③ Team ×3 → Singapore · economy','$528'],
 ['④ Ashley + 3 kids → Rome · ITA nonstop, WED OCT 7','$3,014'],
 ['⑤ Jarred → Rome · Etihad, both legs flat','$2,093'],
 ['⑥ Team ×3 → home · Singapore SQ32 nonstop','$1,393'],
 ['⑦ Rome → Dubrovnik · Ryanair Family Plus ×5','$305'],
 ['⑧ All five → home · London nonstop, 2 flat + 3 economy','$7,364'],
 ['Positioning Dubrovnik → London · Ryanair ×5','$470']],
 gl:'ALL FLIGHTS, ALL 8 TRAVELLERS',gv:'$21,685',
 note:'Swap ⑧ to all-economy and the total drops to <b>$16,676</b>. Swap it to five flat beds out of Dublin and it rises to <b>$27,394</b>.<br><br><b>The family-in-business upgrade, priced honestly.</b> Putting Ashley and the three kids in lie-flat to Rome costs <b>+$10,561</b> on TAP (17h20), <b>+$11,440</b> on BA (15h20), or <b>+$13,848</b> on the Polaris nonstop (11h50) — taking the all-in to <b>$32,246</b>, <b>$33,125</b> or <b>$35,533</b>. If the $10,097 consolidator fare tickets it drops to <b>+$7,083</b> and <b>$28,768</b>, but that is unverified and should not be planned around yet. Hotels and the cruise are separate and already booked.'},
notes:[
{h:'★ BEFORE YOU BOOK — read this first',
 b:'<b>1. Price it live yourself, and expect a list that matches neither of mine.</b> This is not a hedge — it was tested to destruction. One instance ran three passes with <b>cookies and cache cleared</b>; byte-identical every time. The other ran three fresh contexts; byte-identical every time. <b>Neither can see the other\'s British Airways fare no matter how many times either tries.</b> Eight of the nine rows match <b>exactly</b>; the divergence falls <b>entirely on British Airways</b> — one BA itinerary each, mutually exclusive. That pattern is diagnostic rather than random: scattered variance would implicate ranking or caching, but a single carrier differing while eight others hold identical points at <b>ticketing-path or fare-filing visibility keyed to the client</b> — which is coherent with the airline-direct-versus-consolidator split found separately in momondo\'s provider detail. <b>Google Flights serves client-specific inventory.</b> Re-running does not resolve it, and no amount of further checking on my side will. Every cash figure here is one client\'s draw — a strong prior for what to look for, not the fare you will be quoted.<br><br><b>2. Weight the figures by how many independent conditions they survived.</b> <b>TAP $13,575</b> (three sightings, two instances, two dates, zero drift) and <b>United $16,862</b> (every engine, to the dollar, both party encodings) are the two most durable numbers in this entire study. Anything badged <span class="v s">2-SOURCE</span> or <span class="v x">CONFLICTING</span> is a lead, not a price.<br><br><b>3. Two things are genuinely unresolved</b>, and both are stated as open rather than smoothed over: whether the $10,097 consolidator BA fare actually tickets, and the FRA Nov 4 business award row, which is single-axis verified and should be re-checked live before any transfer.<br><br><b>4. ⏰ CANCEL seats.aero BEFORE WED SEP 4</b> or it silently charges $9.99 again. Bought Aug 4 for this research; its one irreplaceable answer was that Croatia has zero business award space, which the free tier could not determine. Self-serve at <b>seats.aero/billing → Stripe portal → Cancel subscription</b>. No refund and no proration, so access runs to Sep 4 either way and cancelling on the last day costs nothing. Full path in <code>/tmp/seatsaero/CANCEL.md</code>; login is an email code, no password, credentials in LastPass under "seats.aero". Receipt #2092-0611, AMEX ...5003.<br><br><b>5. Fly Wed Oct 7.</b> This is the one conclusion that survived every round, every source, both cabins and both markets. ITA does not fly Rome on Thursdays, and Oct 8 carries a brutal premium — the identical Polaris seat is $16,862 on the 7th and $26,334 on the 8th. Departing the 7th still lands the 8th, leaving three clear days before the cruise.'},
{h:'The one points play worth making',
 b:'<b>Qatar Avios, 75,000, for Jarred\'s Singapore → Rome leg.</b> Amex MR transfers 1:1 and that partnership is still live. Against the $2,929 Qsuite cash fare it returns roughly <b>3.5¢ per point</b> — the best redemption found anywhere in this study, and it uses 14% of your pool. Everything else tested came in under 1.5¢ or sat in a program you cannot reach.'},
{h:'⚠ RETRACTION — the Rome "$7,000 saving" was not real',
 b:'<b>I told you a British Airways business fare at $9,492 saved roughly $7,000 over the nonstop. That was wrong, and this note exists so the error is on the record rather than quietly edited away.</b><br><br><b>The $9,492 was never a fare.</b> Traced to its element it is <code>aria-label="9492 US dollars"</code> with no carrier, no stops and no duration — a price-filter control on the page. A text-flattened read landed it beside the words "British Airways" and I reported the pair as a fact. It surfaced only because a second agent tried to reproduce it and could not.<br><br><b>The Oct 7 airline-direct business ladder that survived two independent instances:</b> TAP via Lisbon <b>$13,575</b> (17h20) · United Polaris <b>nonstop $16,862</b> (11h50) · SWISS $16,942 · United 1-stop $16,956 · ITA nonstop $21,270.<br><br><b>The BA row is the one the two instances could not agree on</b> — and the reason turned out to matter more than the fare. Both figures are real, complete rows with full detail; each instance can see one and is blind to the other. Google is serving <b>divergent BA inventory on identical queries</b>. So it is left unpriced rather than averaged, and the broader warning stands: <b>any single-instance cash quote on this route carries variance.</b> TAP earns the recommendation by being the row that never moved.<br><br>Rejected on inspection: JetBlue/Icelandair $13,840 (<b>mixed-cabin recliner, not a bed</b>) and LOT $16,719 (<b>12-hour layover</b>).<br><br><b>Consolidators genuinely sell the same BA seat for $10,097</b> — momondo shows it beside BA\'s own $4,238/pp. <b>Nobody has verified it tickets.</b> It is the only finding that would change the recommendation, and it carries fare-rules risk with a nonrefundable cruise three days behind it.<br><br><b>FIVE instances of ONE failure mode, across five unrelated systems, with zero error messages between them:</b><br>· seats.aero <code>RemainingSeats: 0</code> meaning "not reported," not "none" — hid 18% of bookable inventory<br>· its <code>TotalTaxes: 0</code> meaning "not populated," not "free"<br>· a cabin-class parameter that silently returned economy for both business AND first<br>· ticketing path — an OTA consolidator fare read as an airline-direct price<br>· DOM adjacency — a price-filter widget read as a fare row<br><br>Each one looked like it encoded something, silently encoded something else, and returned a plausible number instead of throwing. <b>Not one of them errored.</b> Every single one was caught only by a second method or a second instance. That is why the badges on this page exist, why "re-check live" appears where it does, and why the figures that survived the most independent conditions deserve more trust than the ones that merely sounded precise.'},
{h:'Why the numbers kept moving — and why these ones should hold',
 b:'Two of the corrections that mattered most in this study came from <b>challenging a comparison, not from searching harder</b>. The Rome award was reported at 3.3¢ per point, then 1.83¢, then 1.69¢ — the award itself never changed once. What changed is that the first number benchmarked a three-flight backtrack against a <i>nonstop</i> cash fare, which inflated it roughly 2×. Pricing the honest denominator is also what surfaced the BA fare that ended up saving $7,000. Separately, filtering award results by seat count killed two findings that had looked clean and specific.<br><br>The durable rule underneath both, and the one worth carrying into the actual booking: <b>a filter asserted at query time and the age of the data it was asserted against are independent failure modes. A result is only trustworthy when both are green.</b> Every "N/A" and every "re-check live" on this page is a place where exactly one of them was.<br><br>Three separate things in this study failed the same way: seats.aero\'s seat counts, its <b>$0</b> tax fields, and a search engine\'s cabin-class parameter. <b>None of them returned an error. All three returned a plausible wrong number instead.</b> That is why the badges exist, and why "re-check live before transferring" appears where it does.'},
{h:'What changed versus what you were told before',
 b:'Delta One is <b>348,500 SkyMiles, not 94,000</b> — out of reach. Flying the team from Sacramento costs <b>$360 more</b>, not $70 less. Dublin <b>does</b> sell five business seats ($13,491) — my earlier "caps at 4" was wrong. The Qatar award is <b>75,000 Avios, not 150,000</b>. ITA does not fly to Rome on Thursdays, which makes Oct 7 worth $2,236 in economy or $9,472 in business. And Amex removed Etihad Guest as a transfer partner on 30 June 2026.'}]
};
