window.__Q__ = {
legs:[
{t:'① Jarred → Seoul, business', d:'Sun 27 Sep · 1 pax · SMF or SFO → ICN',
 opts:[
 {v:'CONFIRMED',n:'Korean Air KE024 — SFO 12:50 → ICN 17:20+1, NONSTOP 12h30',bed:'yes',p:4304,pick:true,
  s:'Median of 4 sources ($4,131 momondo – $4,412 Kayak, 6.8% spread — book the specific source). Prestige. ⚠ 777-300ER rotates between three cabins: the 40-seat 1-2-1 Suites 2.0 and the 42-seat 2-2-2 are both fine, the 56-seat 2-3-2 Sleeper has trapped middles. Check the seat map at booking.'},
 {v:'CONFIRMED',n:'United UA893 — SFO 10:25 → ICN 15:00+1, NONSTOP 12h35, Polaris',bed:'yes',p:4411,
  s:'3 sources exact. True 1-2-1. Points: 87,500 via LifeMiles or Aeroplan (both Amex 1:1) — not United directly.'},
 {v:'CONFLICTING',n:'Asiana OZ211 — SFO 23:20 → ICN 04:25+2, NONSTOP 13h05',bed:'yes',p:'$4,112–4,870',
  s:'A350-900, 28 Business Smartium 1-2-1, 77in bed. Points: 85,000 Aeroplan or LifeMiles, both Amex-reachable.'},
 {v:'CONFIRMED',n:'Delta-branded via Seattle, 16h54 — the cheaper Delta option',bed:'yes',p:4379,
  s:'4 sources. $765 CHEAPER than the itinerary in your app screenshot, and 10 min shorter. Sources disagree on whether the ocean leg is Delta or Korean metal.'},
 {v:'CONFIRMED',n:'Delta One via Seattle, 17h04 — the exact flight in your screenshot',bed:'yes',p:5144,
  s:'3 sources agree to the dollar. A350-900, 32 Delta One suites with doors. POINTS: 348,500 SkyMiles + $6 — you hold 132,931, short by 215,569. Topping up costs 215,569 MR + ~$99 Amex fee and returns 1.48¢/mile. Poor.'},
 {v:'CONFIRMED',n:'Same itinerary, Delta Main Cabin',bed:'no',p:866,s:'If the bed is not worth $4,278.'},
 {v:'CONFLICTING',n:'Same itinerary, Delta Premium Select',bed:'no',p:1411,s:'Recliner, not flat.'}]},

{t:'② The three employees → Seoul, economy', d:'Sun 27 Sep · 3 pax · SFO → ICN',
 opts:[
 {v:'CONFIRMED',n:'Asiana nonstop — SFO 23:20 → ICN 04:25+2',p:1254,pick:true,
  s:'$418 each. Beats every other nonstop by ~$1,050 for the three of them.'},
 {v:'CONFLICTING',n:'China Airlines via Taipei — cheapest 1-stop',p:1725,s:'Not worth the stop for $471.'},
 {v:'CONFIRMED',n:'Korean Air nonstop / United nonstop — both',p:2300,s:'Arrive a day earlier than Asiana.'},
 {v:'CONFIRMED',n:'Delta via Seattle',p:2313,s:'The routing you asked about. Loses.'},
 {v:'CONFIRMED',n:'ORIGIN TEST — same trip out of Sacramento instead',p:1862,
  s:'SFO wins decisively. Fly them from SFO.'},
 {v:'CONFIRMED',n:'POINTS — Aeroplan on Asiana, 50,000/pp',p:'150,000 MR',
  s:'DO NOT USE. 150,000 MR to avoid $1,254 is well under 1¢/point.'}]},

{t:'③ All four men → Singapore', d:'Tue Oct 6 · locked by the Marina Bay Sands booking · ICN → SIN',
 opts:[
 {v:'CONFIRMED',n:'Jarred — Asiana OZ751, ICN 16:10 → SIN 21:30, business',bed:'yes',p:960,pick:true,
  s:'Cheapest AND the best seat of the group. Beats the KE643 you had penciled in by $35.'},
 {v:'CONFIRMED',n:'Jarred — Korean KE643, ICN 13:50 → SIN 19:15 (your original)',bed:'yes',p:995},
 {v:'CONFIRMED',n:'Jarred — Korean KE647 red-eye, ICN 23:35 → SIN 05:00+1',bed:'yes',p:995,s:'Arrives before hotel check-in.'},
 {v:'CONFIRMED',n:'Jarred — T\'way TW161, cheapest "business"',bed:'no',p:623,s:'LCC — not a real business cabin.'},
 {v:'SINGLE-SOURCE',n:'Team ×3, economy',p:528,s:'~$176 each, carried from the earlier live pull. Re-verify.'}]},

{t:'④ Ashley + 3 kids → Rome', d:'4 pax (Ezra and Silas price as adults) · SFO → FCO · THE DATE IS THE DECISION',
 opts:[
 {v:'CONFIRMED',n:'WED OCT 7 — ITA nonstop, 12h, economy',p:3014,pick:true,
  s:'★ ITA\'s AZ641 does NOT fly Thursdays — verified across a 6-day ladder. Oct 8 is also independently the worst-priced day in the window. Departing Oct 7 lands Oct 8 with THREE nights before the cruise instead of two.'},
 {v:'CONFIRMED',n:'WED OCT 7 — United UA507 nonstop, BUSINESS, 4 pax',bed:'yes',p:16862,
  s:'The identical aircraft and seat costs $26,334 on Oct 8. Moving one day saves $9,472.'},
 {v:'CONFIRMED',n:'THU OCT 8 — Condor via Frankfurt, 14h20, economy',p:1485,
  s:'Cheapest sane option if Oct 8 is fixed. "Economy Zero" — no checked bag, add ~$75–100/bag.'},
 {v:'CONFIRMED',n:'THU OCT 8 — Condor premium economy',p:3700,
  s:'3-source confirmed (Google $930 / Kayak $922 / momondo $922 pp). A real premium cabin for four.'},
 {v:'CONFIRMED',n:'THU OCT 8 — SAS via Copenhagen / TAP via Lisbon',p:'$1,936–1,947'},
 {v:'SINGLE-SOURCE',n:'THU OCT 8 — United UA507 nonstop, economy (the only nonstop that day)',p:5250},
 {v:'CONFIRMED',n:'POINTS — Flying Blue premium economy, Oct 8 only, 4 seats live-verified',p:'358,000 MR + $996',
  s:'0.76¢/point against the $3,700 cash equivalent. Burns ~$4,000 of value.'},
 {v:'CONFIRMED',n:'POINTS — the ONLY business-on-points that fits: Flying Blue via LONDON, Oct 8',bed:'yes',p:'454,000 MR + $1,810',
  s:'★ REAL — 113,500/pp, 4 seats, live-verified 100%. But read the shape before you like it: it is AIR FRANCE/KLM metal, NOT Virgin, and NOT nonstop. The journey is SFO → Paris or Amsterdam → London → Rome: THREE FLIGHTS, TWO TICKETS, flying past Rome to Paris, back northwest to London, then southeast to Rome. Lie-flat only on the first segment; the London hop is a euro recliner and the Rome leg is a separate economy ticket. Arrives Oct 9 — two days of cruise buffer, not three. Uses 86% of your pool. The 3.3¢/pt figure is flattered because it is benchmarked against a NONSTOP cash fare; the honest denominator is a connecting business fare nobody has priced, so the real number is lower. Why the ugly routing: Flying Blue business straight to Rome is 194,500/pp = 778,000 for four, over your pool. Routing via London is the only way it fits at all.'},
 {v:'CONFIRMED',n:'POINTS — everything else in business, both dates',p:'does not fit',
  s:'Flying Blue direct to Rome 778,000 · Turkish 700,000 · both over your 525,382. Lufthansa 309,540 is Miles & More, unreachable. A BA Avios 99,000 at $0 fees looked perfect and VANISHED when tested at 4 seats — a phantom in cached data.'}]},

{t:'⑤ Jarred → Rome', d:'Sat 10 Oct · 1 pax · SIN → FCO · must clear the Fri Oct 9 party and beat Oct 11 boarding',
 opts:[
 {v:'CONFIRMED',n:'Etihad via Abu Dhabi — both legs genuine lie-flat',bed:'yes',p:2093,pick:true,
  s:'Best fit for the constraint. ⚠ Amex → Etihad Guest was REMOVED 30 Jun 2026, so this is a cash buy.'},
 {v:'CONFIRMED',n:'Saudia via Jeddah, dep 02:20 — cheapest true lie-flat',bed:'yes',p:1588,
  s:'$505 less than Etihad. The 2:20am departure is the cost.'},
 {v:'CONFIRMED',n:'Emirates A380 on BOTH legs — true 1-2-1 throughout',bed:'yes',p:2423},
 {v:'CONFIRMED',n:'Emirates, the cheap one everyone books — THE TRAP',bed:'no',p:2222,
  s:'Not lie-flat. $201 less than the real A380 product for a materially worse seat.'},
 {v:'CONFLICTING',n:'Qatar Qsuite via Doha — best seat on the day',bed:'yes',p:2929},
 {v:'CONFIRMED',n:'★ THE 150,000-AVIOS QUESTION, RESOLVED: it is 75,000',p:'75,000 Avios',
  s:'Qatar Privilege Club, and Amex MR → Qatar Avios IS still live. My earlier 150,000 reading was wrong. At 75,000 against a $2,929 cash fare this is roughly 3.5¢/point — the best redemption in the entire study.'}]},

{t:'⑥ The three employees → home', d:'Sat 10 Oct · 3 pax · SIN → SFO or SMF',
 opts:[
 {v:'CONFIRMED',n:'Singapore Airlines SQ32 nonstop → SFO, bag-eligible fare',p:1393,pick:true,
  s:'$464 each on a nonstop. The winner.'},
 {v:'CONFIRMED',n:'Vietnam Airlines via Ho Chi Minh City',p:1473,s:'More stops, more money. No.'},
 {v:'CONFIRMED',n:'United nonstop, BASIC economy',p:1758,s:'$1,926 for the standard bag-eligible fare.'},
 {v:'CONFIRMED',n:'Through to Sacramento — Air Canada',p:1753,
  s:'⚠ VERDICT ON THE OLD CLAIM: flying them to SMF costs $360 MORE than SFO, not $70. The prior note was wrong.'}]},

{t:'⑦ Rome → Dubrovnik', d:'Sun 18 Oct · 5 pax · after the cruise',
 opts:[
 {v:'CONFIRMED',n:'Ryanair FR5975 nonstop — Family Plus bundle',p:305,pick:true,
  s:'The realistic booking for five with multi-week luggage. Basic fare alone is $115 but that is cabin-bag-only.'},
 {v:'CONFIRMED',n:'Ryanair FR5975 nonstop — Basic fare',p:115,s:'Under-seat bag only. Unrealistic here.'},
 {v:'CONFLICTING',n:'Croatia Airlines OU385 nonstop — the only alternative',p:825,
  s:'Timing does not work against the disembarkation. Ruled out on feasibility, not price.'},
 {v:'UNAVAILABLE',n:'ITA and Vueling nonstops',p:null,s:'Neither operates this route.'}]},

{t:'⑧ All five → home', d:'Oct 25 – Nov 3 · 5 pax · Europe → SFO · THE BIG ONE',
 opts:[
 {v:'CONFIRMED',n:'5 IN ECONOMY — London LHR → SFO, British Airways NONSTOP',p:2355,pick:true,
  s:'The winner for economy. Add ~$470 Ryanair from Dubrovnik.'},
 {v:'CONFIRMED',n:'2 BUSINESS + 3 ECONOMY — Dublin, cheapest business seats',bed:'yes',p:7047,pick:true,
  s:'The cheapest way to get two people flat. Booked as two separate PNRs.'},
 {v:'CONFIRMED',n:'2 BUSINESS + 3 ECONOMY — London, everyone on the nonstop',bed:'yes',p:7364,
  s:'$317 more than Dublin and nobody connects. Probably worth it.'},
 {v:'CONFIRMED',n:'5 IN BUSINESS — Dublin EI61 NONSTOP',bed:'yes',p:13491,
  s:'★ CORRECTS my earlier claim that five-in-business does not exist at Dublin. It does. A330, Thompson-style flat bed.'},
 {v:'CONFIRMED',n:'5 IN BUSINESS — London, Virgin VS19 NONSTOP',bed:'yes',p:14888,
  s:'$1,397 more than Dublin for the Upper Class cabin.'},
 {v:'CONFIRMED',n:'POINTS — nothing reachable for five in business',p:'none',
  s:'Every European business award that survived verification sits in Lufthansa Miles & More, Alaska, American or United. None take Amex points.'}]}
],
totals:{h:'The recommended plan, all cash, all confirmed',
 rows:[
 ['① Jarred → Seoul · Korean KE024 nonstop','$4,304'],
 ['② Team ×3 → Seoul · Asiana nonstop','$1,254'],
 ['③ Jarred → Singapore · Asiana OZ751 business','$960'],
 ['③ Team ×3 → Singapore · economy','$528'],
 ['④ Ashley + 3 kids → Rome · ITA nonstop, WED OCT 7','$3,014'],
 ['⑤ Jarred → Rome · Etihad, both legs flat','$2,093'],
 ['⑥ Team ×3 → home · Singapore SQ32 nonstop','$1,393'],
 ['⑦ Rome → Dubrovnik · Ryanair Family Plus ×5','$305'],
 ['⑧ All five → home · London nonstop, 2 flat + 3 economy','$7,364'],
 ['Positioning Dubrovnik → London · Ryanair ×5','$470']],
 gl:'ALL FLIGHTS, ALL 8 TRAVELLERS',gv:'$21,685',
 note:'Swap ⑧ to all-economy and the total drops to <b>$16,676</b>. Swap it to five flat beds out of Dublin and it rises to <b>$27,394</b>. Hotels and the cruise are separate and already booked.'},
notes:[
{h:'The one points play worth making',
 b:'<b>Qatar Avios, 75,000, for Jarred\'s Singapore → Rome leg.</b> Amex MR transfers 1:1 and that partnership is still live. Against the $2,929 Qsuite cash fare it returns roughly <b>3.5¢ per point</b> — the best redemption found anywhere in this study, and it uses 14% of your pool. Everything else tested came in under 1.5¢ or sat in a program you cannot reach.'},
{h:'The Rome decision, framed honestly',
 b:'This is a real choice, not an answer, and it is yours. <b>$16,862 cash</b> buys a single-ticket United Polaris <b>nonstop</b> on Wed Oct 7, 11h50, lie-flat the whole way, landing with three clear days before the cruise. <b>454,000 Membership Rewards plus ~$1,810</b> buys three flights across two tickets on Oct 8 — SFO to Paris or Amsterdam, back to London, then down to Rome — flat only on the first leg, no misconnect protection between tickets, a terminal transfer, a bag re-check, and two days of buffer instead of three. With four people and an eight-year-old, the backtrack is a heavier ask than the arithmetic suggests. I would fly Oct 7 and pay cash, but the points version genuinely exists and I am not going to pretend it does not.'},
{h:'What changed versus what you were told before',
 b:'Delta One is <b>348,500 SkyMiles, not 94,000</b> — out of reach. Flying the team from Sacramento costs <b>$360 more</b>, not $70 less. Dublin <b>does</b> sell five business seats ($13,491) — my earlier "caps at 4" was wrong. The Qatar award is <b>75,000 Avios, not 150,000</b>. ITA does not fly to Rome on Thursdays, which makes Oct 7 worth $2,236 in economy or $9,472 in business. And Amex removed Etihad Guest as a transfer partner on 30 June 2026.'}]
};
